#!./bin/ruby

require "uri"
require_relative 'cfn2dsl_lib/cfn2dsl'

payload = URI.decode(JSON.parse(ARGV[0])["body"].tr('+', ' ')).gsub(/^code\=/,'')
template = JSON.parse(payload)
cfndsl   = CloudFormation.new(template)
dsl = Render.new(cfndsl).cfn_to_cfndsl

dsl = "require 'cfndsl'\n\n" \
      "# Generated by https://cfnflip.com/\n" \
      "# The 'cfndsl' gem is required. Type `gem install cfndsl` to install it.\n\n" \
      "#{dsl.gsub(/^CloudFormation\ do/, 'template = CloudFormation do')}\n" \
      "puts template.to_json"

puts dsl
